-- setup based off https://www.youtube.com/watch?v=vdn_pKJUda8
-- shout out to Josean Martinez :)
require("default.plugins-setup")
require("default.core.options")
require("default.core.keymaps")
require("default.core.colorscheme")
require("default.plugins.comment")
require("default.plugins.nvim-tree")
require("default.plugins.lualine")
require("default.plugins.telescope")
require("default.plugins.nvim-cmp")
require("default.plugins..mason")
require("default.plugins.lsp.lspsaga")
require("default.plugins.lsp.lspconfig")
require("default.plugins.lsp.null-ls")
require("default.plugins.autopairs")
require("default.plugins.treesitter")
require("default.plugins.gitsigns")
